### ISSUE TITLE
Doesn't work with very simple usecase

### ISSUE THREAD

**Issue by dehghani-mehdi** [lmgonzalves/pieces#1]
Hi,

With following:

```
<canvas class="my-canvas"></canvas>

<script src="anime.js"></script>
<script src="pieces.js"></script>
<script>
	var options = {
		canvas: '.my-canvas',
		text: 'Hello World',
		piecesWidth: 10,
		angle: 35
	};
	var myPieces = new Pieces(options);
	myPieces.showPieces();
</script>
```

I got this:

![untitled](https://user-images.githubusercontent.com/9152330/41509170-266180a4-7265-11e8-9844-35dfa29adb5c.png)

I'm using latest version of `anime.js` and `pieces.js`, btw I'm using Firefox, latest version.

**Comment by lmgonzalves** [comment]
It works as expected...

Please active the `debug` option and you can see what is happening:
https://jsfiddle.net/zetqsnku/3

Then, setting a bigger `width` for the `canvas` in CSS, and using the `extraSpacing` option will fix the issue:
https://jsfiddle.net/zetqsnku/7/

**Comment by dehghani-mehdi** [comment]
Actually you know the secrets of your code, so for you works as expected.
This peace of info not exist in docs, so maybe you should try to update the docs.

Also the library should smart enough to run without any issue with provided options. anyway thanks for helping here.
